FROM node:16-alpine AS base-stage

WORKDIR /app

COPY package.json \
    yarn.lock \
    ./

RUN apk add --no-cache --virtual .gyp \
    python3 \
    make \
    g++ \
    && yarn --frozen-lockfile --network-timeout 600000 \
    && yarn cache clean \
    && apk del .gyp 

##############################################################
FROM base-stage AS build-stage 

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npm run build

FROM node:16-alpine

COPY --from=build-stage /app/node_modules ./node_modules
COPY --from=build-stage /app/package*.json ./
COPY --from=build-stage /app/dist ./dist

EXPOSE 3000

CMD [ "npm", "run", "start:migrate:prod" ]